config/routes.rb
Plohish::Application.routes.draw do
  resources :oversights

  match 'mark/:id/:mark' => 'oversights#mark'
  match 'mee_too/:id' => 'oversights#mee_too'
  match 'auth' => 'vk_user#auth'

  root :to => "title#index"

end

app/models/mark.rb
class Mark
  include Mongoid::Document

  referenced_in :vk_user
  referenced_in :oversight

  field :value, :type => Integer
end

app/models/mee_too.rb
class MeeToo
  include Mongoid::Document

  field :joined, :type => DateTime

  referenced_in :vk_user
  referenced_in :oversight

  before_create :update_timestamp

  def update_timestamp
    self.joined = DateTime.now
  end
end

app/models/oversight.rb
class Oversight
  include Mongoid::Document

  referenced_in :vk_user
  references_many :marks
  references_many :mee_toos

  field :text
  field :rating, :type => Integer
  field :created, :type => DateTime

  validates_presence_of :text

  before_create :update_timesamps, :empty_marks, :empty_mee_too

  @_mee_too_users = nil

  def user
    ''
  end

  def update_timesamps
    self.created = DateTime.now
  end

  def empty_marks
    self.marks = []
  end

  def empty_mee_too
    self.mee_toos = []
  end

  def is_marked_by?(user)
    Mark.all(:conditions => {:vk_user_id => user._id, :oversight_id => self._id}).count > 0
  end

  def duplicated_by_user?(user)
    MeeToo.all(:conditions => {:vk_user_id => user._id, :oversight_id => self._id}).count > 0
  end

  def place_mark(user, mark)
    mark = Mark.create(:mark => mark)
    user.marks << mark
    self.marks << mark
  end

  def mark
    mark = 0
    self.marks.each { |m| mark += m.mark }
    mark
  end

  def mee_too_users
    if @_mee_too_users.nil?
      @_mee_too_users = []
      self.mee_toos.each do |mee_too|
        @_mee_too_users.push(mee_too.vk_user) if !mee_too.vk_user.nil?
      end
    end
    @_mee_too_users
  end

  class << self
    def top(limit = 10)
      Oversight.order_by(:rating).limit(limit).all
    end

    def last(limit = 10)
      Oversight.order_by(:created.desc).limit(limit).all
    end
  end
end

app/models/vk_user.rb
class VkUser
  include Mongoid::Document

  references_many :oversights
  references_many :marks
  references_many :mee_toos

  field :uid
  field :first_name
  field :last_name
  field :sex, :type => Integer
  field :city, :type => Integer
  field :country, :type => Integer
  field :photo 
  field :registered, :type => DateTime

  index :uid, :unique => true

  before_create :update_timestamps, :empty_marks, :empty_mee_too

  def update_timestamps
    self.registered = DateTime.now
  end

  def empty_marks
    self.marks = []
  end

  def empty_mee_too
    self.mee_toos = []
  end

  def name
    name = []
    [self.first_name, self.last_name].each do |n|
      name << n if !n.nil?
    end
    name.join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/oversights_controller.rb
class OversightsController < ApplicationController
  # POST /oversights
  def create
    @user = VkUser.find(session[:user])
    if !@user.nil?
      @oversight = Oversight.new(params[:oversight])
      @oversight.save
      @user.oversights << @oversight
    end
    respond_to do |format|
      format.html { redirect_to('/') }
    end
  end

  def mark
    @user = VkUser.find(session[:user])
    @oversight = Oversight.find(params[:id])
    if !@user.nil? && !@oversight.nil? && !@oversight.is_marked_by?(@user) 
      mark = params[:mark] == 'dislike'? -1 : 1
      @oversight.place_mark(@user, mark)
    end
    respond_to do |format|
      format.html { redirect_to('/') }
    end
  end

  def mee_too
    @user = VkUser.find(session[:user])
    @oversight = Oversight.find(params[:id])
    if !@user.nil? && !@oversight.nil? && !@oversight.duplicated_by_user?(@user)
      mee_too = MeeToo.create()
      @oversight.mee_toos << mee_too
      @user.mee_toos << mee_too
    end
    respond_to do |format|
      format.html { redirect_to('/') }
    end
  end
end

app/controllers/title_controller.rb
class TitleController < ApplicationController
  def index
    @oversights = Oversight.last(30)
    @form = Oversight.new
    @user = VkUser.find(session[:user]) if !session[:user].nil?
  end
end

app/controllers/vk_user_controller.rb
class VkUserController < ApplicationController
  def auth
    user_data = params[:user]
    user = VkUser.find_or_create_by(:uid => user_data['uid'])
    user.update_attributes(user_data)
    user.save!
    session[:user] = user._id
    respond_to do |format|
      format.html { render :status => 200, :text => '' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oversights_helper.rb
module OversightsHelper
  def vk_user_link(user)
    return 'anonimous' if !user.kind_of? VkUser
    link_to user.name, vk_user_url(user)
  end

  def vk_user_url(user)
    return '' if !user.kind_of? VkUser
    'http://vkontakte.ru/id%d' % [user.uid]
  end

  def vk_user_avatar(user)
    if user.kind_of? VkUser
      image_tag(user.photo, :alt => user.name) if !user.photo.nil?
    end
  end
end

app/helpers/title_helper.rb
module TitleHelper
end

app/helpers/vk_user_helper.rb
module VkUserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plohish</title>
  <%= stylesheet_link_tag :all %>
	<%= javascript_include_tag 'http://vkontakte.ru/js/api/xd_connection.js?2' %>
  <%= javascript_include_tag 's/jq.js' %>
  <%= javascript_include_tag 's/ui.js' %>
  <%= javascript_include_tag 's/json.js' %>
  <%= javascript_include_tag 's/sminpt.js' %>
  <%= javascript_include_tag 's/i.js' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/oversights/_form.html.erb
<%= form_for(@oversight) do |f| %>
  <% if @oversight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oversight.errors.count, "error") %> prohibited this oversight from being saved:</h2>

      <ul>
      <% @oversight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/oversights/edit.html.erb
<h1>Editing oversight</h1>

<%= render 'form' %>

<%= link_to 'Show', @oversight %> |
<%= link_to 'Back', oversights_path %>

app/views/oversights/index.html.erb
<h1>Listing oversights</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @oversights.each do |oversight| %>
  <tr>
    <td><%= link_to 'Show', oversight %></td>
    <td><%= link_to 'Edit', edit_oversight_path(oversight) %></td>
    <td><%= link_to 'Destroy', oversight, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Oversight', new_oversight_path %>

app/views/oversights/new.html.erb
<h1>New oversight</h1>

<%= render 'form' %>

<%= link_to 'Back', oversights_path %>

app/views/oversights/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_oversight_path(@oversight) %> |
<%= link_to 'Back', oversights_path %>

app/views/title/_form.html.erb
<span id='first_name'><%= @user.first_name %></span>,  есть о чем расказать?
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this oversight from being saved:</h2>
      <ul>
      <% @form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div id='form-userpic'>
    <% if !@user.photo.nil? %>
      <img src='<%= @user.photo %>' alt='<%= @user.name %>' />
    <% end %>
  <img
  </div>
  <div class='fields'>
    <ul>
      <li>
        <%= f.text_area :text, :suggest => 'Что натворил?', :rows => 5, :cols => 50 %>
      </li>
    </ul>
  </div>

  <div class="actions">
    <%= submit_tag('Добавить') %>
  </div>
<% end %>

app/views/title/_list.html.erb
<% if @oversights.length > 0 %>
  <%= render :partial => 'oversight', :collection => @oversights %>
<% else %>
  <strong>плохих поступков пока никто не совершил видимо</strong>
<% end %>

app/views/title/_oversight.html.erb
<%= link_to vk_user_avatar(oversight.vk_user), vk_user_url(oversight.vk_user) %>
<strong><%= vk_user_link(oversight.vk_user) %></strong>
<div class='oversight'>
  <%= h(oversight.text) %>
</div>
<div class='marks'>
  <%= link_to '+', url_for(:controller => :oversights, :action => :mark, :id => oversight._id, :mark => 'like') %> 
  <%= oversight.mark.to_i %> 
  <%= link_to '–', url_for(:controller => :oversights, :action => :mark, :id => oversight._id, :mark => 'dislike') %>
  <% users = oversight.mee_too_users %>
  <% users_count = users.count %>
  <strong>+1:</strong>
  <% users.each_with_index do |u, i| %>
    <%= vk_user_link(u) %><%= '' if i < users_count %> 
  <% end %>
  <%= link_to 'я тоже', url_for(:controller => :oversights, :action => :mee_too, :id => oversight._id) %>
</div>

app/views/title/index.html.erb
<% if @user.nil? %>
  <script>auth('<%= url_for(:controller => :vk_user, :action => :auth) %>')</script>
<% else %>
  <h3>Хорошими делами прославиться нельзя. Зато можно попытаться плохими. Давай, расскажи всем что ты сегодня сделал плохого.</h3>
  <div class='oversight-list'>
    <%= render :partial => 'list' %>
  </div>
  <div class='form'>
    <%= render :partial => 'form' %>
  </div>
  <script>init()</script>
<% end %>